import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { Container, Nav, Navbar, Stack } from 'react-bootstrap';
import Hero from '../components/Hero';
import Social from '../components/Social';
import TopBar from '../components/TopBar';

export default function Home({ data }) {
  const [title, setTitle] = useState([]);

  useEffect(() => {
    data.map((item) => {
      setTitle(item.title);
    });
  }, [data]);

  return (
    <>
      <Head>
        <title>Posting Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-light shadow-sm">
        <Container>
          <Stack direction="horizontal" gap={3}>
            <span className="d-flex align-items-center gap-2">
              <Image
                src="/icons/bullhorn-solid.svg"
                alt="Image"
                height={16}
                width={16}
              />

              <span className="text-muted fw-bold">{title + '.'}</span>
            </span>
            <span className="d-none d-md-block ms-auto">
              <Social />
            </span>
          </Stack>
        </Container>
        <TopBar />
      </div>
      <Hero />
    </>
  );
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`http://0.0.0.0:3000/api/blogs`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
