import Head from 'next/head';
import TopAlertBar from '../components/TopAlertBar';
import TopBar from '../components/TopBar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Posting Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopAlertBar />
      <TopBar />
    </>
  );
}
